sudo: false
language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.4.1
  - MRUBY_VERSION=master
# matrix:
#   allow_failures:
#     - env: MRUBY_VERSION=master
branches:
  only:
    - master

addons:
  apt:
    packages:
      - rake
      - bison
      - git
script:
  - rake format
  - rake test
